lists/urls.py
from django.urls import path
from lists import views

urlpatterns = [
    path('new', views.new_list, name='new_list'),
    path('<int:list_id>/', views.view_list, name='view_list'),
]

movielists/urls.py
from django.urls import include, path
from lists import views as list_views
from lists import urls as list_urls

urlpatterns = [
    path('', list_views.home_page, name='home'),
    path('lists/', include(list_urls)),
]

lists/models.py
from django.db import models
from django.urls import reverse


class List(models.Model):
    
    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])


class Movie(models.Model):
    title = models.TextField(default='')
    movielist = models.ForeignKey(List, default=None, on_delete=models.CASCADE,)

lists/views.py
from django.shortcuts import redirect, render
from django.core.exceptions import ValidationError

from lists.models import Movie, List


def home_page(request):
    if request.method == 'POST':
        Movie.objects.create(title=request.POST['movie_title'])
        return redirect('/lists/the-only-list-in-the-world/')
    return render(request, 'home.html')


def view_list(request, list_id):
    movie_list = List.objects.get(id=list_id)
    error = None

    if request.method == 'POST':
        try:
            new_movie = Movie(title=request.POST['movie_title'], movielist=movie_list)
            new_movie.full_clean()
            new_movie.save()
            return redirect(movie_list)
        except ValidationError:
            error = "You can't have an empty movie title"

    return render(request, 'list.html', {'list': movie_list, 'error': error})


def new_list(request):
    movie_list = List.objects.create()
    new_movie = Movie.objects.create(title=request.POST['movie_title'], movielist=movie_list)
    try:
        new_movie.full_clean()
        new_movie.save()
    except ValidationError:
        movie_list.delete()
        error = "You can't have an empty movie title"
        return render(request, 'home.html', {"error": error})
    return redirect(movie_list)

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Movie Lists</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      
      <div class="row">
        <div class="col-md-6 offset-md-3 jumbotron">
          <div class="text-center">
            <h1>{% block header_text %} {% endblock %}</h1>
            <form method="POST" action='{% block form_action %}{% endblock %}'>
              <input name="movie_title" id="id_new_movie" 
                     class ="form-control input-lg"
                     placeholder="Enter a movie title" />
              {% csrf_token %}
              {% if error %}
                <div class="form-group has-error">
                  <span class="help-block">{{ error }}</span>
                </div>
              {% endif %}
            </form>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 offset-md-3">
          {% block table %}
          {% endblock %}
        </div>
      </div>

    </div>
  </body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new Movie list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your Movie List{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
   <table id="id_movie_table" class="table">
     {% for movie in list.movie_set.all %}
       <tr><td>{{ forloop.counter }}: {{ movie.title }}</td></tr>
     {% endfor %}
   </table>
{% endblock %}